/* Vendor the Little Kickers agreement + pricing engine into the site's edge
 * functions.
 * ---------------------------------------------------------------------------
 *     node tools/vendor-lk.js          (run from the barestkd-site folder)
 *
 * WHY: lk-checkout (the public Little Kickers enrollment function) must
 * freeze the SAME agreement text the CRM uses and price with the SAME engine
 * the POS uses. Deno functions can't reach across repos at deploy time, so
 * both are vendored here — and tests/lk-checkout.test.js fails if either
 * copy drifts from its source in BaresCRM.
 *
 * WHEN TO RUN: after regenerating BaresCRM/agreements.js (attorney revision)
 * or changing BaresCRM pricing_esm.js. Then redeploy lk-checkout.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const SITE = path.join(__dirname, '..');
const CRM = path.join(SITE, '..', 'BaresCRM');
const OUT = path.join(SITE, 'supabase', 'functions', '_shared');

// 1) The Little Kickers template, lifted from the generated agreements.js.
const A = require(path.join(CRM, 'agreements.js'));
const tpl = A.TEMPLATES.find((t) => t.key === 'little_kickers');
if (!tpl) throw new Error('agreements.js has no little_kickers template');
fs.writeFileSync(path.join(OUT, 'lk_agreement.js'),
  '// GENERATED by tools/vendor-lk.js from BaresCRM/agreements.js (version '
  + tpl.version + ').\n'
  + '// Do NOT hand-edit — the drift test compares this against the CRM copy.\n'
  + 'export default ' + JSON.stringify(tpl, null, 2) + ';\n');
console.log('wrote _shared/lk_agreement.js (template version ' + tpl.version + ')');

// 2) The pricing engine, byte-for-byte from the CRM's own vendored copy.
const src = path.join(CRM, 'supabase', 'functions', '_shared', 'pricing_esm.js');
fs.copyFileSync(src, path.join(OUT, 'pricing_esm.js'));
console.log('copied _shared/pricing_esm.js (' + fs.statSync(src).size + ' bytes)');
