/* Vendor the Little Kickers agreement + pricing engine into the site's edge
 * functions.
 * ---------------------------------------------------------------------------
 *     node tools/vendor-lk.js          (run from the barestkd-site folder)
 *
 * WHY: lk-checkout (the public Little Kickers enrollment function) must
 * freeze the SAME agreement text the CRM uses and price with the SAME engine
 * the POS uses. Deno functions can't reach across repos at deploy time, so
 * both are vendored here — and tests/lk-checkout.test.js fails if either
 * copy drifts from its source in BaresCRM.
 *
 * WHEN TO RUN: after regenerating BaresCRM/agreements.js (attorney revision)
 * or changing BaresCRM pricing_esm.js. Then redeploy lk-checkout.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const SITE = path.join(__dirname, '..');
const CRM = path.join(SITE, '..', 'BaresCRM');
const OUT = path.join(SITE, 'supabase', 'functions', '_shared');

// 1) One vendored template per program with a self-serve checkout page,
//    lifted from the generated agreements.js.
const A = require(path.join(CRM, 'agreements.js'));
const VENDORED = [
  { key: 'little_kickers', file: 'lk_agreement.js' },
  { key: 'cubs', file: 'cubs_agreement.js' },
  // The remaining programs that transact self-serve. `taekwondo` covers BOTH
  // Juniors and Teens/Adults - one attorney-approved document, two pages.
  { key: 'taekwondo', file: 'taekwondo_agreement.js' },
  { key: 'kickboxing', file: 'kickboxing_agreement.js' },
  { key: 'jiujitsu', file: 'jiujitsu_agreement.js' },
  { key: 'ampd', file: 'ampd_agreement.js' },
];
for (const v of VENDORED) {
  const tpl = A.TEMPLATES.find((t) => t.key === v.key);
  if (!tpl) throw new Error('agreements.js has no ' + v.key + ' template');
  fs.writeFileSync(path.join(OUT, v.file),
    '// GENERATED by tools/vendor-lk.js from BaresCRM/agreements.js (version '
    + tpl.version + ').\n'
    + '// Do NOT hand-edit — the drift test compares this against the CRM copy.\n'
    + 'export default ' + JSON.stringify(tpl, null, 2) + ';\n');
  console.log('wrote _shared/' + v.file + ' (template version ' + tpl.version + ')');
}

// 2) The pricing engine, byte-for-byte from the CRM's own vendored copy.
const src = path.join(CRM, 'supabase', 'functions', '_shared', 'pricing_esm.js');
fs.copyFileSync(src, path.join(OUT, 'pricing_esm.js'));
console.log('copied _shared/pricing_esm.js (' + fs.statSync(src).size + ' bytes)');
